"""fix schema

Revision ID: 623004c2a51f
Revises: 001_initial
Create Date: 2026-03-12 04:34:14.452289
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '623004c2a51f'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'trace_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               comment='关联任务ID',
               existing_nullable=False)
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'topic',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               comment='事件主题, e.g. task.created',
               existing_nullable=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               comment='事件类型, e.g. state.changed',
               existing_nullable=False)
    op.alter_column('events', 'producer',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               comment='事件生产者, e.g. orchestrator:v1',
               existing_nullable=False)
    op.alter_column('events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='事件负载',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('events', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='元数据 {priority, model, version}',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index('ix_events_trace_topic', 'events', ['trace_id', 'topic'], unique=False)
    op.add_column('tasks', sa.Column('id', sa.String(length=32), nullable=False, comment='任务ID, e.g. JJC-20260301-001'))
    op.add_column('tasks', sa.Column('org', sa.String(length=32), nullable=False, comment='当前执行部门'))
    op.add_column('tasks', sa.Column('official', sa.String(length=32), nullable=True, comment='责任官员'))
    op.add_column('tasks', sa.Column('now', sa.Text(), nullable=True, comment='当前进展描述'))
    op.add_column('tasks', sa.Column('eta', sa.String(length=64), nullable=True, comment='预计完成时间'))
    op.add_column('tasks', sa.Column('block', sa.Text(), nullable=True, comment='阻塞原因'))
    op.add_column('tasks', sa.Column('output', sa.Text(), nullable=True, comment='最终产出'))
    op.add_column('tasks', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('template_id', sa.String(length=64), nullable=True, comment='模板ID'))
    op.add_column('tasks', sa.Column('template_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='模板参数'))
    op.add_column('tasks', sa.Column('ac', sa.Text(), nullable=True, comment='验收标准'))
    op.add_column('tasks', sa.Column('target_dept', sa.String(length=64), nullable=True, comment='目标部门'))
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               comment='任务标题',
               existing_nullable=False)
    op.alter_column('tasks', 'state',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Taizi', 'Zhongshu', 'Menxia', 'Assigned', 'Next', 'Doing', 'Review', 'Done', 'Blocked', 'Cancelled', 'Pending', name='task_state'),
               existing_nullable=False,
               existing_server_default=sa.text("'taizi'::character varying"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               comment='优先级',
               existing_nullable=True,
               existing_server_default=sa.text("'中'::character varying"))
    op.alter_column('tasks', 'flow_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='流转日志 [{at, from, to, remark}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tasks', 'progress_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='进展日志 [{at, agent, text, todos}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tasks', 'todos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='子任务 [{id, title, status, detail}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tasks', 'scheduler',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='调度器元数据',
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tasks_assignee_org'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_tags'), table_name='tasks', postgresql_using='gin')
    op.drop_index(op.f('ix_tasks_trace_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_archived'), 'tasks', ['archived'], unique=False)
    op.create_index('ix_tasks_state_archived', 'tasks', ['state', 'archived'], unique=False)
    op.create_index('ix_tasks_updated_at', 'tasks', ['updated_at'], unique=False)
    op.drop_column('tasks', 'trace_id')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'task_id')
    op.drop_column('tasks', 'assignee_org')
    op.drop_column('tasks', 'creator')
    op.drop_column('tasks', 'meta')
    op.drop_column('tasks', 'description')
    op.add_column('thoughts', sa.Column('source', sa.String(length=16), nullable=True, comment='来源: llm|tool|human'))
    op.add_column('thoughts', sa.Column('sensitive', sa.Boolean(), nullable=True, comment='是否敏感内容'))
    op.add_column('thoughts', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('thoughts', 'trace_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               comment='关联任务ID',
               existing_nullable=False)
    op.alter_column('thoughts', 'agent',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               comment='Agent 标识',
               existing_nullable=False)
    op.alter_column('thoughts', 'step',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='思考步骤序号',
               existing_server_default=sa.text('0'))
    op.alter_column('thoughts', 'type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=32),
               comment='思考类型: reasoning|query|action_intent|summary',
               existing_nullable=False)
    op.alter_column('thoughts', 'content',
               existing_type=sa.TEXT(),
               comment='思考内容',
               existing_nullable=False)
    op.alter_column('thoughts', 'tokens',
               existing_type=sa.INTEGER(),
               comment='消耗 token 数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('thoughts', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='置信度 0-1',
               existing_nullable=True)
    op.create_index('ix_thoughts_timestamp', 'thoughts', ['timestamp'], unique=False)
    op.create_index('ix_thoughts_trace_agent', 'thoughts', ['trace_id', 'agent'], unique=False)
    op.drop_column('thoughts', 'created_at')
    op.drop_column('thoughts', 'meta')
    op.add_column('todos', sa.Column('trace_id', sa.String(length=32), nullable=False, comment='关联任务ID'))
    op.add_column('todos', sa.Column('description', sa.Text(), nullable=True, comment='详细描述'))
    op.add_column('todos', sa.Column('owner', sa.String(length=64), nullable=True, comment='负责部门'))
    op.add_column('todos', sa.Column('assignee_agent', sa.String(length=32), nullable=True, comment='执行 Agent'))
    op.add_column('todos', sa.Column('estimated_cost', sa.Float(), nullable=True, comment='预估 token 耗费'))
    op.add_column('todos', sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建者'))
    op.alter_column('todos', 'parent_id',
               existing_type=sa.UUID(),
               comment='父级 todo_id（树状结构）',
               existing_nullable=True)
    op.alter_column('todos', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=256),
               comment='子任务标题',
               existing_nullable=False)
    op.alter_column('todos', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               nullable=False,
               comment='状态: open|in_progress|done|cancelled',
               existing_server_default=sa.text("'not-started'::character varying"))
    op.alter_column('todos', 'priority',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=16),
               comment='优先级: low|normal|high|urgent',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('todos', 'checkpoints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='检查点 [{name, status}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('todos', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='扩展元数据',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('todos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('todos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_todos_task_id'), table_name='todos')
    op.create_index(op.f('ix_todos_trace_id'), 'todos', ['trace_id'], unique=False)
    op.create_index('ix_todos_trace_status', 'todos', ['trace_id', 'status'], unique=False)
    op.drop_constraint(op.f('todos_task_id_fkey'), 'todos', type_='foreignkey')
    op.drop_constraint(op.f('todos_parent_id_fkey'), 'todos', type_='foreignkey')
    op.drop_column('todos', 'detail')
    op.drop_column('todos', 'assignee')
    op.drop_column('todos', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('todos', sa.Column('assignee', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('detail', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('todos_parent_id_fkey'), 'todos', 'todos', ['parent_id'], ['todo_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('todos_task_id_fkey'), 'todos', 'tasks', ['task_id'], ['task_id'], ondelete='CASCADE')
    op.drop_index('ix_todos_trace_status', table_name='todos')
    op.drop_index(op.f('ix_todos_trace_id'), table_name='todos')
    op.create_index(op.f('ix_todos_task_id'), 'todos', ['task_id'], unique=False)
    op.alter_column('todos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('todos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('todos', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='扩展元数据',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('todos', 'checkpoints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='检查点 [{name, status}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('todos', 'priority',
               existing_type=sa.String(length=16),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='优先级: low|normal|high|urgent',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('todos', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='状态: open|in_progress|done|cancelled',
               existing_server_default=sa.text("'not-started'::character varying"))
    op.alter_column('todos', 'title',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='子任务标题',
               existing_nullable=False)
    op.alter_column('todos', 'parent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='父级 todo_id（树状结构）',
               existing_nullable=True)
    op.drop_column('todos', 'created_by')
    op.drop_column('todos', 'estimated_cost')
    op.drop_column('todos', 'assignee_agent')
    op.drop_column('todos', 'owner')
    op.drop_column('todos', 'description')
    op.drop_column('todos', 'trace_id')
    op.add_column('thoughts', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('thoughts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index('ix_thoughts_trace_agent', table_name='thoughts')
    op.drop_index('ix_thoughts_timestamp', table_name='thoughts')
    op.alter_column('thoughts', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='置信度 0-1',
               existing_nullable=True)
    op.alter_column('thoughts', 'tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='消耗 token 数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('thoughts', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='思考内容',
               existing_nullable=False)
    op.alter_column('thoughts', 'type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='思考类型: reasoning|query|action_intent|summary',
               existing_nullable=False)
    op.alter_column('thoughts', 'step',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='思考步骤序号',
               existing_server_default=sa.text('0'))
    op.alter_column('thoughts', 'agent',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Agent 标识',
               existing_nullable=False)
    op.alter_column('thoughts', 'trace_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='关联任务ID',
               existing_nullable=False)
    op.drop_column('thoughts', 'timestamp')
    op.drop_column('thoughts', 'sensitive')
    op.drop_column('thoughts', 'source')
    op.add_column('tasks', sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('creator', sa.VARCHAR(length=50), server_default=sa.text("'emperor'::character varying"), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('assignee_org', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('task_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('trace_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index('ix_tasks_updated_at', table_name='tasks')
    op.drop_index('ix_tasks_state_archived', table_name='tasks')
    op.drop_index(op.f('ix_tasks_archived'), table_name='tasks')
    op.create_index(op.f('ix_tasks_trace_id'), 'tasks', ['trace_id'], unique=False)
    op.create_index(op.f('ix_tasks_tags'), 'tasks', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_assignee_org'), 'tasks', ['assignee_org'], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'scheduler',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='调度器元数据',
               existing_nullable=True)
    op.alter_column('tasks', 'todos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='子任务 [{id, title, status, detail}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tasks', 'progress_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='进展日志 [{at, agent, text, todos}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tasks', 'flow_log',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='流转日志 [{at, from, to, remark}]',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='优先级',
               existing_nullable=True,
               existing_server_default=sa.text("'中'::character varying"))
    op.alter_column('tasks', 'state',
               existing_type=sa.Enum('Taizi', 'Zhongshu', 'Menxia', 'Assigned', 'Next', 'Doing', 'Review', 'Done', 'Blocked', 'Cancelled', 'Pending', name='task_state'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'taizi'::character varying"))
    op.alter_column('tasks', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='任务标题',
               existing_nullable=False)
    op.drop_column('tasks', 'target_dept')
    op.drop_column('tasks', 'ac')
    op.drop_column('tasks', 'template_params')
    op.drop_column('tasks', 'template_id')
    op.drop_column('tasks', 'archived')
    op.drop_column('tasks', 'output')
    op.drop_column('tasks', 'block')
    op.drop_column('tasks', 'eta')
    op.drop_column('tasks', 'now')
    op.drop_column('tasks', 'official')
    op.drop_column('tasks', 'org')
    op.drop_column('tasks', 'id')
    op.drop_index('ix_events_trace_topic', table_name='events')
    op.alter_column('events', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='元数据 {priority, model, version}',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='事件负载',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('events', 'producer',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='事件生产者, e.g. orchestrator:v1',
               existing_nullable=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='事件类型, e.g. state.changed',
               existing_nullable=False)
    op.alter_column('events', 'topic',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='事件主题, e.g. task.created',
               existing_nullable=False)
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'trace_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='关联任务ID',
               existing_nullable=False)
    # ### end Alembic commands ###
